# Generated by Django 6.0 on 2025-12-29 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.TextField(choices=[('Perfume', 'Perfume'), ('Desodorante', 'Desodorante')])),
                ('capacidade', models.IntegerField()),
                ('preco', models.FloatField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.marca')),
            ],
        ),
    ]
