# Generated by Django 6.0 on 2025-12-30 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_produto_quantidade_alter_produto_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='loja.marca'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Desodorante', 'Desodorante'), ('Colônia', 'Colonia'), ('Body splash', 'Body Splash'), ('Sabonete', 'Sabonete'), ('Esfoliante', 'Esfoliante'), ('Óleo corporal', 'Oleo Corporal'), ('Hidratante', 'Hidratante'), ('Proteção solar', 'Protecao Solar'), ('Álcool em gel', 'Alcool Gel'), ('Shampoo', 'Shampoo'), ('Condicionador', 'Condicionador'), ('Máscara de tratamento', 'Mascara'), ('Finalizador', 'Finalizador')], max_length=35),
        ),
    ]
