# Generated by Django 6.0 on 2025-12-31 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_marca_ativo_produto_ativo_alter_produto_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-31T10:30:00Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-31T10:30:00Z'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='loja.marca'),
        ),
    ]
