# Generated by Django 5.2.9 on 2026-01-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_produto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
